# Generated by Django 5.2.16 on 2026-07-23 06:21

import apps.bitaturno.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'área',
                'verbose_name_plural': 'áreas',
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='TipoNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'tipo de novedad',
                'verbose_name_plural': 'tipos de novedad',
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=180, verbose_name='título')),
                ('descripcion_inicial', models.TextField(blank=True, verbose_name='descripción inicial')),
                ('prioridad', models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='', max_length=5, verbose_name='prioridad')),
                ('estado_registro', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REGISTRADA', 'Registrada')], default='BORRADOR', editable=False, max_length=10, verbose_name='estado del registro')),
                ('estado_operacional', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('CERRADA', 'Cerrada')], default='', max_length=11, verbose_name='estado operacional')),
                ('fecha_ocurrencia', models.DateTimeField(blank=True, help_text='Opcional. Corresponde al momento informado por el usuario.', null=True, verbose_name='fecha y hora de ocurrencia')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True, verbose_name='fecha de captura')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='fecha de finalización')),
                ('fecha_cierre', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='fecha de cierre')),
                ('fotografia', models.ImageField(blank=True, help_text='Opcional. JPEG, PNG o WEBP; máximo 5 MB.', upload_to='novedades/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'), message='Formato no permitido. Use JPEG, PNG o WEBP.'), apps.bitaturno.models.validar_tamano_fotografia], verbose_name='fotografía')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='bitaturno.area', verbose_name='área')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='bitaturno.disciplina', verbose_name='disciplina')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='bitaturno.equipo', verbose_name='equipo')),
                ('tipo_novedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='bitaturno.tiponovedad', verbose_name='tipo de novedad')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='bitaturno.turno', verbose_name='turno')),
            ],
            options={
                'verbose_name': 'novedad',
                'verbose_name_plural': 'novedades',
                'ordering': ('-fecha_captura', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('estado_operacional', ''), ('estado_registro', 'BORRADOR')), models.Q(('estado_operacional__in', ('PENDIENTE', 'EN_REVISION', 'CERRADA')), ('estado_registro', 'REGISTRADA')), _connector='OR'), name='bitaturno_estado_registro_operacional_valido')],
            },
        ),
    ]
