# Generated by Django 5.2.16 on 2026-07-29 06:05

import apps.bitaturno.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitaturno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='fotografia',
            field=models.ImageField(blank=True, help_text='Opcional. JPEG, PNG o WEBP; máximo 10 MB.', upload_to='novedades/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'), message='Formato no permitido. Use JPEG, PNG o WEBP.'), apps.bitaturno.models.validar_tamano_fotografia], verbose_name='fotografía'),
        ),
    ]
