# Generated by Django 5.2.16 on 2026-07-31 07:27

import uuid
from django.db import migrations, models


MODELOS = (
    "Area",
    "Disciplina",
    "Equipo",
    "Novedad",
    "TipoNovedad",
    "Turno",
)


def asignar_uuid_portables(apps, schema_editor):
    for nombre_modelo in MODELOS:
        modelo = apps.get_model("bitaturno", nombre_modelo)
        for pk in modelo.objects.filter(portable_id__isnull=True).values_list(
            "pk",
            flat=True,
        ):
            modelo.objects.filter(pk=pk).update(portable_id=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('bitaturno', '0003_alter_novedad_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='portable_id',
            field=models.UUIDField(editable=False, null=True, verbose_name='identificador portable'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='portable_id',
            field=models.UUIDField(editable=False, null=True, verbose_name='identificador portable'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='portable_id',
            field=models.UUIDField(editable=False, null=True, verbose_name='identificador portable'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='portable_id',
            field=models.UUIDField(editable=False, null=True, verbose_name='identificador portable'),
        ),
        migrations.AddField(
            model_name='tiponovedad',
            name='portable_id',
            field=models.UUIDField(editable=False, null=True, verbose_name='identificador portable'),
        ),
        migrations.AddField(
            model_name='turno',
            name='portable_id',
            field=models.UUIDField(editable=False, null=True, verbose_name='identificador portable'),
        ),
        migrations.RunPython(
            asignar_uuid_portables,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='area',
            name='portable_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador portable'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='portable_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador portable'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='portable_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador portable'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='portable_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador portable'),
        ),
        migrations.AlterField(
            model_name='tiponovedad',
            name='portable_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador portable'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='portable_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador portable'),
        ),
    ]
