# Generated by Django 5.2.16 on 2026-07-31 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portable_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador')),
                ('tipo', models.CharField(choices=[('EXPORTACION', 'Exportación'), ('IMPORTACION', 'Importación')], max_length=12, verbose_name='tipo')),
                ('estado', models.CharField(choices=[('INSPECCIONADA', 'Inspeccionada'), ('COMPLETADA', 'Completada'), ('SIMULADA', 'Simulada'), ('CANCELADA', 'Cancelada'), ('FALLIDA', 'Fallida')], max_length=14, verbose_name='estado')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='fecha de término')),
                ('secciones', models.JSONField(default=list, verbose_name='secciones')),
                ('opciones', models.JSONField(default=dict, verbose_name='opciones')),
                ('politica', models.CharField(blank=True, choices=[('OMITIR', 'Omitir existentes'), ('ACTUALIZAR', 'Actualizar existentes'), ('DETENER', 'Detener ante conflictos')], max_length=10, verbose_name='política de conflictos')),
                ('nombre_paquete', models.CharField(max_length=255, verbose_name='nombre del paquete')),
                ('sha256_paquete', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('tamano_paquete', models.PositiveBigIntegerField(default=0, verbose_name='tamaño')),
                ('archivo_ruta', models.CharField(blank=True, max_length=500, verbose_name='ruta interna')),
                ('respaldo_previo', models.CharField(blank=True, max_length=500, verbose_name='respaldo previo')),
                ('conteos', models.JSONField(default=dict, verbose_name='conteos')),
                ('resultado', models.JSONField(default=dict, verbose_name='resultado')),
                ('errores', models.TextField(blank=True, verbose_name='errores')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_datos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'transferencia de datos',
                'verbose_name_plural': 'transferencias de datos',
                'ordering': ('-fecha_inicio', '-pk'),
                'permissions': [('can_manage_data_transfers', 'Puede administrar transferencias de datos')],
            },
        ),
    ]
